### PR TITLE
Update Japanese translation

### PR DESCRIPTION
**Pull request by karu323**
Translated an article of aigismod into Japanese.
This is my first time translating and using github, so I apologize for any inadequacies.

### CODE REVIEW

**Comment by karu323** [comment]
Translated an article of aigismod into Japanese.
This is my first time translating and using github, so I apologize for any inadequacies.

**Comment by dimensionPlayer** [comment]
Thanks for the translation files and some bugs and observations on the mod. In a few days, i will upload your translation along with some bug fixing. Do you have a Steam account for easier communication?

**Comment by dimensionPlayer** [comment]
Thanks for the translation files and some bugs and observation on the mod.
In a few days, I will upload your translation along with some bug fixing.
Do you have a Steam account for easier communication?

**Comment by karu323** [comment]
I don't have.

**Comment by dimensionPlayer** [comment]
To who the credits for the translation should go? Is fine to use your
GitHub username in the credits?

**Comment by karu323** [comment]
Yes, please.

**Comment by dimensionPlayer** [comment]
Thanks for translating the mod to Japanese, the mod has been updated with
the translation.

Also, thanks for the additional notes on bugs and observations, they helped
a lot on improving the mod.

**Pull request closed without merging**
