### PR TITLE
Adding Korean translation 16/02/23

### PR DESCRIPTION
**Pull request by P0N-CHAN**
Hi, I recently knew that there is a StS mod based on Aigis.
As I am a huge fan of both games, I couldn't help making the Korean version of it.

There might be some typos and minor errors because I made it in a rush & this is my first time using github and json stuffs.
But at least during my testing I found no critical error, so I thought this would help Korean gamers to enjoy your fantastic mod.

Thanks for making this mod. I've really enjoyed it.
I will try to update this regularly.

### CODE REVIEW

**Comment by dimensionPlayer** [comment]
Hi.

Thanks for helping me with the mod.  

You can message me here when you want me to update the mod with your translation in the Steam Workshop. Also if you have questions you can put them here.

**Comment by P0N-CHAN** [comment]
Yesterday I asked my friends to tell me if they found any error while playing the translated version, so finding & fixing the minor errors will take about one day. I will write a comment here when I am ready to upload the translated version to workshop.

**Comment by P0N-CHAN** [comment]
I finished revising the translations. You can upload it to the workshop.
Would you mind writing my name as Pon-chan in the credit? (not P0N-CHAN)

Thanks again for making this mod, and see you in next the update!

**Comment by P0N-CHAN** [comment]
I finished revising the translations. You can upload it to the workshop.
Would you mind writing my name as Pon-chan in the credit? (not P0N-CHAN)

Thanks again for making this mod, and see you in next the update!

**Comment by P0N-CHAN** [comment]
I finished revising the translations. You can upload it to the workshop.
Would you mind writing my name as Pon-chan in the credit? (not P0N-CHAN)

Thanks again for making this mod, and see you in the next update!

**Comment by P0N-CHAN** [comment]
I finished revising the translations. You can upload it to the workshop.
Would you mind writing my name as Pon-chan in the credit? (not P0N-CHAN)

Thanks again for making this mod, and see you in the next update!

**Pull request merged**
